#include "cpu/exec.h"

make_EHelper(mov);

make_EHelper(operand_size);

make_EHelper(inv);
make_EHelper(nemu_trap);

make_EHelper(push);//下面都是我写的optable>_<
make_EHelper(pop);//按添加的顺序排列
make_EHelper(call);
make_EHelper(sub);
make_EHelper(xor);
make_EHelper(ret);
make_EHelper(lea);
make_EHelper(and);
make_EHelper(test);
make_EHelper(jcc);
make_EHelper(cmp);
make_EHelper(setcc);
make_EHelper(movzx);
make_EHelper(movsx);
make_EHelper(jmp);
make_EHelper(leave);
make_EHelper(add);
make_EHelper(inc);
make_EHelper(xchg);
make_EHelper(cltd);
make_EHelper(idiv);
make_EHelper(shr);
make_EHelper(sar);
make_EHelper(shl);
make_EHelper(dec);
make_EHelper(adc);
make_EHelper(sbb);
make_EHelper(or);
make_EHelper(imul1);
make_EHelper(imul2);
make_EHelper(imul3);
make_EHelper(call_rm);
make_EHelper(test);
make_EHelper(not);
make_EHelper(jmp_rm);
make_EHelper(idiv);
make_EHelper(div);
make_EHelper(mul);
make_EHelper(in);
make_EHelper(out);
make_EHelper(cwtl);
make_EHelper(neg);
make_EHelper(rcl);
make_EHelper(rcr);
make_EHelper(rol);
make_EHelper(ror);
make_EHelper(lidt);
make_EHelper(int);
make_EHelper(pusha);
make_EHelper(popa);
make_EHelper(iret);
